### ISSUE TITLE
Problemer med ultraSonic sensorene

### ISSUE THREAD

**Issue by aasmune** [mazzus/RoboCar#16]
Testet ut HC-SR04 sensorene mine nå, både med koden fra da vi jobbet sammen og også den som ligger ute på GitHub. Får bare 0 som output hele tiden. Virker som at dere ikke har hatt samme problem, men ser ut som mange andre har samme problem  ut i fra denne linken: http://forum.arduino.cc/index.php?topic=55119.0

Noen forslag til hvordan vi kan løse det?

**Comment by mazzus** [comment]
hvis de ikke virker selv om det er noe foran dem så er det en annen feil. For den du linket til er bare at de henger seg opp om det ikke er noe innenfor rekkevidde

**Comment by aasmune** [comment]
Men er det ikke at de henger seg dersom det ikke er noe innenfor rekkevidde, og at de dermed ikke vil virke etter det selv om det er noe foran dem?

**Comment by aasmune** [comment]
Kan likevel hende at det fungerer dersom vi putter på en pulldown resistor på trigger og echo da jeg jeg har sjekket at echo er konstant lik 2

**Comment by mazzus** [comment]
Ja, vi får se :)

**Comment by aasmune** [comment]
Fått sensoren til å fungere forholdsvis bra nå :)
Tar å skriver et alternativt bibliotek til den som baserer seg på biblioteket NewPing

**Comment by aasmune** [comment]
Nytt bibliotek er på plass.
Problemet er nå løst :)
Løsningen var å sette echoPin til OUTPUT og sette den til LOW før man endrer den til INPUT rett etter man leser av sensoren. På den måten hindrer man at echoPin står konstant som HIGH dersom den ikke leser av noe :)
